### ISSUE TITLE
Compute Git repo secret reference

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-api#42]
Generate the name of the git repo secret reference in https://github.com/projectsyn/lieutenant-api/blob/master/pkg/api/utils.go#L193 by parsing the `gitRepo` field. Use the subdomain and domain as identifier: `ssh://git@git.example.net/syn/cluster-catalogs/mycatalog.git` would generate the secret name `git.example.net`.

Document this behavior and also add a note that with this approach git software running in a path (f.e. git.example.net/mygitlab) isn't supported.

**Comment by srueg** [comment]
I don't like this "computing" of the secret name very much. Maybe we can add a filed to the tenant object, like the one proposed in https://github.com/projectsyn/lieutenant-operator/issues/48 ?

```
spec.clusterCataloGitRepo:
  baseURL: ssh://git@git.example.net/syn/cluster-catalogs/
  apiSecretRef:
    name: git-example-credentials
```
